ansible_user: ec2-user
ansible_password: DevOps321
MONGODB_HOST: mongodb-dev.tzpcsystems.xyz
CATALOGUE_HOST: catalogue-dev.tzpcsystems.xyz
REDIS_HOST: redis-dev.tzpcsystems.xyz
USER_HOST: user-dev.tzpcsystems.xyz
CART_HOST: cart-dev.tzpcsystems.xyz
MYSQL_HOST: mysql-dev.tzpcsystems.xyz
SHIPPING_HOST: shipping-dev.tzpcsystems.xyz
RABBITMQ_HOST: rabbitmq-dev.tzpcsystems.xyz
PAYMENT_HOST: payment-dev.tzpcsystems.xyz