[mongodb]
mongodb-dev.tzpcsystems.xyz

[catalogue]
catalogue-dev.tzpcsystems.xyz

[redis]
redis-dev.tzpcsystems.xyz

[user]
user-dev.tzpcsystems.xyz

[cart]
cart-dev.tzpcsystems.xyz

[mysql]
mysql-dev.tzpcsystems.xyz

[shipping]
shipping-dev.tzpcsystems.xyz

[rabbitmq]
rabbitmq-dev.tzpcsystems.xyz

[payment]
payment-dev.tzpcsystems.xyz

[frontend]
frontend-dev.tzpcsystems.xyz
