- name: Copy {{ component }}.service file
  ansible.builtin.template:
    src: "{{ component }}.service.j2"
    dest: /etc/systemd/system/{{ component }}.service
  when: component in ["catalogue", "user", "cart", "shipping", "payment"]

- name: start {{ component }}
  ansible.builtin.service:
    state: restarted
    name: "{{ component }}"
    enabled: yes