- name: Copy {{ component }}.service file
  ansible.builtin.template:
    src: "{{ component }}.service.j2"
    dest: /etc/systemd/system/{{ component }}.service
    # remote_src: true
  when: component in ["catalogue", "user", "cart", "shipping", "payment"]
  # when:
  # - component == "catalogue" or
  # - component == "user" or
  # - component == "cart" or
  # - component == "shipping" or
  # - component == "payment"

- name: start {{ component }}
  ansible.builtin.service:
    state: restarted
    name: "{{ component }}"
    enabled: yes